
# This workflow will check for Black formating, install Python dependencies using Anaconda, and then run tests with a single version of Python.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run linting and tests with Anaconda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs the schedule every day at 5:30 and at 17:30 UTC
    - cron:  '30 5,17 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update -f tutorials/Guides_for_contributors/environment.yaml -n base
        pip install -e .
    - name: Run unmarked tests only
      run: |
        pytest
# I can't figure out permissions to run these tests... so I skip them for now 
# and just run them locally.
#    - name: Run no_django_setup marked tests
#     run: |
#       sudo /usr/share/miniconda/bin/pytest -m no_django_setup -p no:django
